apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_dem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-secret-app
  template:
    metadata:
      labels:
        app: config-secret-app
    spec:
      containers:
      - name: webapp
        image: chakribaggam123/demo:77
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
